"""add study_group_notes

Revision ID: 68ce403fbd55
Revises: b8e4f2a91c3d
Create Date: 2026-07-10 11:33:04.261935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ce403fbd55'
down_revision = 'b8e4f2a91c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
